---
apiVersion: v2
appVersion: 6.0.0
description: A Helm chart to deploy the oso proposal handling tool
home: https://gitlab.com/ska-telescope/oso/ska-oso-pht
maintainers:
  - email: stargazer@sarao.ac.za
    name: STARGAZER
name: ska-oso-pht-ui
version: 6.0.0